### ISSUE TITLE
Eternal Upload

### ISSUE THREAD

**Issue by davisidarta** [pinellolab/STREAM#10]
Hello there, STREAM Team! 

I've found your tool most interesting! However, I'm still struggling to use it - files seem to keep uploading forever.

This happens for both your web tool and the docker image which I run on our local computing cluster.

Besides, I get this error on my server Linux command line interface when the docker image starts running:

```
`[2019-04-08 21:33:52,331] ERROR in app: Exception on /compute/_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 556, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 513, in add_context
    output_value = func(*args, **kwargs)
  File "/stream_web/app.py", line 2145, in update_matrix_log
    with open(UPLOADS_FOLDER + '/params.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/UPLOADS_FOLDER/STREAM_fff4a25f-f5f4-4fb7-98e3-6adbd84f6a0b/params.json'
```

I'm trying to upload a raw counts dataset of about 1500 cells (which really isn't much).

Is there any way of goint through this? Am I doing anything wrong? 

Thanks for the help in advance!

Best regards,

Davi

**Comment by huidongchen** [comment]
Hi Davi,

Would you mind sharing with us the dataset you are using? We tried the upload part and it works fine for us. I'm happy to take a look for you.

Currently the website is hosted on a small machine. I would suggesting running the docker version website locally. 

The error you saw doesn't matter. The file 'params.json' will be generated automatically each time you open the web page.

Huidong

**Comment by lucapinello** [comment]
Hi @davisidarta 

We have updated the website, could you please try again?

**Comment by davisidarta** [comment]
It works fine on the website now, but the docker version won't go. I'm running it on a Linux Ubuntu 18.04.2 LTS server. Connection doesn't seem to be the issue, neither docker - everything else on docker and on the server work fine.

I've uploaded the files I'm using here:

Labels - https://ufile.io/5ouz7c2f
Raw Counts - https://ufile.io/qtrbvxgt

I'm sorry for the late response. Floods have been harsh in Brazil this week.

Thank you already for your help!

Davi

**Comment by huidongchen** [comment]
Hi @Davi, sorry about the floods there. I hope everything is going well with you.

I tried to download the files you shared but unfortunately the links don't work.

Our website is running on the latest STREAM docker image. If it works fine on the website, it should work the same for the docker image. Did you update your Docker image? If not, can you try:

`docker pull pinellolab/stream_web`

Tutorial can be found here [https://github.com/pinellolab/STREAM_web](url)

This will update it to the latest version. Let me know how it goes.

Huidong
