### ISSUE TITLE
Generation of adata.h5ad by using motif specific command line and Cell Ranger output files

### ISSUE THREAD

**Issue by sylestiel** [pinellolab/STREAM#101]
Hi,

 I have tried several times to generate the adata.h5ad, zscores_scaled.tsv.gz, and zscores.tsv.gz files using command line and the following script and my cellranger output data:

$ stream_atac -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output

Although it worked with no problem for ~3K cells dataset it appears to going on endlessly for a dataset with >7K  cells.

I let it run for a couple of weeks and then closed it. Can you suggest a way to expedite the generation of adata and zscore files.

Thank you!

**Comment by huidongchen** [comment]
Hi, 

Sorry about the error. Instead of running `stream_atac`, can you try to run the R script [run_preprocess.R](https://github.com/pinellolab/STREAM_atac/blob/master/stream_atac/run_preprocess.R) directly in the same environment?

```R
Rscript ./run_preprocess.R -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output
```
It might be something related to the package `rpy2`.

**Comment by huidongchen** [comment]
Also to speed up the whole procedure, you can try to increase `n_jobs`. STREAM internally calls `chromVAR` to get the zscore matrix. Just for your reference, in our previous [benchmark study](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1854-5), with ~5k cells and 44 cpus, the part takes ~30 mins

**Comment by sylestiel** [comment]
Thank you! I will give it a try.

**Comment by sylestiel** [comment]
You wrote : _can you try to run the R script run_preprocess.R directly in the same environment?_

Is this in Terminal or in Jupyter Notebook. Need more clarification.

**Comment by huidongchen** [comment]
`Rscript ./run_preprocess.R -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output` needs to be run in your terminal. You can simply replace your stream_atac command line with the Rscript command line.

**Comment by sylestiel** [comment]
So do I start of by 
conda activate myenv
R
Rscript ./run_preprocess.R -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output

**Comment by huidongchen** [comment]
First, you need to download the script [run_preprocess.R](https://github.com/pinellolab/STREAM_atac/blob/master/stream_atac/run_preprocess.R) to your local machine (e.g. under the directory `~/your_workdir`

Then in your terminal, 
```bash 
conda activate myenv
Rscript ~/your_workdir/run_preprocess.R -c ./filtered_peak_bc_matrix/matrix.mtx -r ./filtered_peak_bc_matrix/peaks.bed -s ./filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output
```

You are all set!

**Comment by sylestiel** [comment]
$ Rscript /Volumes/BKUP2/R_projects/Stream/run_preprocess.R -c /Volumes/BKUP2/scATAC_data/72020_scATAC/SH2_E165/outs/filtered_peak_bc_matrix/matrix.mtx -r /Volumes/BKUP2/scATAC_data/72020_scATAC/SH2_E165/outs/filtered_peak_bc_matrix/peaks.bed -s /Volumes/BKUP2/scATAC_data/72020_scATAC/SH2_E165/outs/filtered_peak_bc_matrix/barcodes.tsv --file_format mtx -g mm10 -f motif --n_jobs 3 -o stream_output
### Error: unexpected '<' in "<"
Execution halted


Can you catch the error here?

**Comment by huidongchen** [comment]
Sorry I am not sure about this error. I gave it a try on an example data. it works well on my machine.

**Comment by sylestiel** [comment]
I appear to have downloaded the html version of run_preprocess.R

How can I download the actual executable?

Thanks!

**Comment by sylestiel** [comment]
It is working. I downloaded the wrong file previously.

**Comment by huidongchen** [comment]
Awesome. once it's finished, you can run the following code snippet to read it into STREAM-compatible object

```python
import pandas as pd
import anndata as ad
import stream as st
df_zscores = pd.read_csv('zscores.tsv.gz',sep='\t',index_col=0)
adata = ad.AnnData(X=df_zscores_scaled.values.T, obs={'obs_names':df_zscores_scaled.columns},var={'var_names':df_zscores_scaled.index})
st.set_workdir(adata,'./stream_result')
```

**Comment by sylestiel** [comment]
<img width="1110" alt="Screen Shot 2020-12-14 at 4 07 20 PM" src="https://user-images.githubusercontent.com/64283689/102141477-7ce51780-3e26-11eb-800b-fbcd4e89ed89.png">

**Comment by huidongchen** [comment]
As I showed above, you need to import several other libraries:

```python
import pandas as pd
import anndata as ad
from sklearn import preprocessing
import stream as st
```

**Comment by sylestiel** [comment]
Having downloaded them.
Do I import them using 
conda import pandas as pd and so on?
Alternatively, do I open up Juypter notebook and run the  motif ipynb?

**Comment by sylestiel** [comment]
Hi,

A new error:

<img width="1146" alt="Screen Shot 2020-12-16 at 12 13 43 PM" src="https://user-images.githubusercontent.com/64283689/102389301-842c3280-3f98-11eb-9a10-53e723b92c83.png">


Suggestions?

**Comment by huidongchen** [comment]
> Awesome. once it's finished, you can run the following code snippet to read it into STREAM-compatible object
> 
> ```python
> import pandas as pd
> import anndata as ad
> from sklearn import preprocessing
> import stream as st
> df_zscores = pd.read_csv('zscores.tsv.gz',sep='\t',index_col=0)
> df_zscores_scaled = preprocessing.scale(df_zscores,axis=1)
> df_zscores_scaled = pd.DataFrame(df_zscores_scaled,index=df_zscores.index,columns=df_zscores.columns)
> adata = ad.AnnData(X=df_zscores_scaled.values.T, obs={'obs_names':df_zscores_scaled.columns},var={'var_names':df_zscores_scaled.index})
> st.set_workdir(adata,'./stream_result')
> ```

Instead of `st.read()`, please use the above codes I mentioned  before

**Comment by sylestiel** [comment]
I did do that as shown in the first chuck of the script posted above.

Is it not done in Jupyter notebook

**Comment by huidongchen** [comment]
You don't need to run the step4 and step7 in your notebook.

You can skip to step 8 in this [tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/2.3.STREAM_scATAC-seq_motifs.ipynb?flush_cache=true)

**Comment by sylestiel** [comment]
Thank you very much Huidong!
