### ISSUE TITLE
map_new_data align two sets poorly in umap.

### ISSUE THREAD

**Issue by ccshao** [pinellolab/STREAM#109]
I have two dataset generated in one batch, let's say one is ko and the other is wt. I tried to align the ko to wt, however, the results suggested poor alignment.  If needed I could provide the raw count data. Suggestions are highly appreciated. Thanks!

Below are the essential codes.
## wt stream
```
import stream as st

st.set_figure_params(dpi=300,
                     style='white',
                     figsize=[6.4, 5.8],
                     rc={'image.cmap': 'viridis'})

#- >> Process the wt data.
adata = st.read(file_name='wt_count.tsv.gz',
                workdir='./stream_result')
st.add_metadata(adata, file_name='wt_meta.tsv')
st.cal_qc(adata, assay='rna')
st.filter_features(adata, min_n_cells=3)
#- <<

#- >> !! Important for later alignment.
adata_ko = st.read(file_name='ko_count.tsv.gz',
                   workdir='./mapping/')
st.add_metadata(adata_ko, file_name='ko_meta.tsv')
st.cal_qc(adata_ko, assay='rna')
st.filter_features(adata_ko, min_n_cells=3)
#- <<

tgene    = adata.var.index.intersection(adata_ko.var.index)
adata    = adata[:, tgene].copy()
adata_ko = adata_ko[:, tgene].copy()

st.normalize(adata, method='lib_size')
st.log_transform(adata)
st.remove_mt_genes(adata)

st.normalize(adata_ko, method='lib_size')
st.log_transform(adata_ko)
st.remove_mt_genes(adata_ko)

st.write(adata, file_name="adata_basic.pkl")
st.write(adata_ko, file_name="adata_ko_basic.pkl")
del adata_ko

st.select_variable_genes(adata, save_fig=True)

#- Set the method to umap so alignment could be used.
st.dimension_reduction(adata,
                       n_components=2,
                       method='umap',
                       feature='var_genes',
                       n_jobs=12)

st.plot_dimension_reduction(adata,
                            color=['label', 'n_genes'],
                            n_components=2,
                            show_graph=False,
                            show_text=False,
                            save_fig=True)

st.seed_elastic_principal_graph(adata)
st.plot_branches(adata, show_text=True, save_fig=True, fig_name='branches.png')

st.elastic_principal_graph(adata, epg_alpha=0.1)
st.plot_branches(adata,
                 show_text=False,
                 save_fig=True,
                 fig_name='branches2.png')

st.extend_elastic_principal_graph(adata, epg_ext_mode='QuantCentroid', reset=True, epg_ext_par=0.05)
st.plot_dimension_reduction(adata,
                            color=['label'],
                            n_components=2,
                            show_graph=True,
                            show_text=True,
                            save_fig=True,
                            fig_name='dimension_reduction2.png')

st.plot_branches(adata,
                 show_text=True,
                 fig_name='branches3.png',
                 save_fig=True)

st.plot_flat_tree(adata,
                  color=['label', 'S1_pseudotime'],
                  show_graph=True,
                  show_text=True,
                  save_fig=True)

st.plot_stream_sc(adata,
                  root='S1',
                  color=['label', 'S1_pseudotime'],
                  dist_scale=0.3,
                  show_graph=True,
                  show_text=True,
                  save_fig=True)

st.plot_stream(adata, root='S1', color=['label'], save_fig=True)
st.write(adata, file_name='stream_result.pkl')
```

## mapping
```
import stream as st

st.set_figure_params(dpi=300,
                     style='white',
                     figsize=[6.4, 5.8],
                     rc={'image.cmap': 'viridis'})

adata_ko = st.read(file_name='adata_ko_basic.pkl')
adata_wt = st.read(file_name='stream_result.pkl')
adata_ko.var.columns = 'ko_' + adata_ko.var.columns

adata_all = st.map_new_data(adata_wt, adata_ko)
adata_all.obs['batch'] = adata_all.obs['batch'].astype(str)
torep = {'ref': 'wt', 'new': 'ko'}
adata_all.obs['batch'] = adata_all.obs['batch'].replace(torep, regex=False)

st.plot_dimension_reduction(adata_all,
                            color=['label', 'batch'],
                            show_graph=True,
                            show_text=False,
                            save_fig=True,
                            fig_name='dimension_reduction.png')

st.plot_visualization_2D(adata_all,
                         n_neighbors=30,
                         color=['label', 'batch'],
                         fig_ncol=4,
                         save_fig=True,
                         fig_name='vis_2d.png')

st.plot_stream_sc(adata_all,
                  root='S1',
                  color=['label', 'batch'],
                  dist_scale=0.5,
                  show_graph=True,
                  save_fig=True,
                  show_text=True)

st.plot_stream(adata_all,
               root='S1',
               color=['label', 'batch'],
               save_fig=True,
               dist_scale=1.2)

st.write(adata_wt, file_name='adata_wt.pkl')
st.write(adata_ko, file_name='adata_ko.pkl')
st.write(adata_all, file_name='adata_all.pkl')

```

## dimension reduction and map stream
The dimension reduction suggested the ko and wt are not well aligned, also shown on the stream results.
![dimension_reduction-fs8](https://user-images.githubusercontent.com/4980631/103565190-2c5e5880-4ec0-11eb-9877-1bab2140d74b.png)
<img width="749" alt="Screenshot 2021-01-04 at 19 06 49-fs8" src="https://user-images.githubusercontent.com/4980631/103565191-2d8f8580-4ec0-11eb-88a4-70f6fb8489da.png">
![vis_2d-fs8](https://user-images.githubusercontent.com/4980631/103565193-2ec0b280-4ec0-11eb-9277-6470a6e11e3e.png)

**Comment by huidongchen** [comment]
Yeah, in STREAM, we are implementing a naive procedure to project new data to the reference by simply fitting new data to the model trained on reference. This only works if the assumption that batch effect doesn't exist holds.

In your case, I think you might want to take a look at scRNA-seq batch correction methods that are dedicated to this scenario.

**Comment by ccshao** [comment]
To be honest I don’t think it is batch effect. They are generated in a single experiments. We have used Seurat/scanpy and found no batch effect at all. 

Actually, the mystery thing is that the two data sets matched very well, until I sub-sampled the ko to have equal number of cells in two conditions.

I was thinking that I made simple mistakes in the codes. Could you kindly check the codes I used? I am also glad to share the raw data with you, if an email address is given. Many thanks!

**Comment by huidongchen** [comment]
hmmm, that's good to know. The mapping procedure should work then. Yeah, I am happy to take a closer look. huidong.chen[at]mgh.harvard.edu

**Comment by huidongchen** [comment]
> To be honest I don’t think it is batch effect. They are generated in a single experiments. We have used Seurat/scanpy and found no batch effect at all. Actually, the mystery thing is that the two data sets matched very well, until I sub-sampled the ko to have equal number of cells in two conditions. I was thinking that I made simple mistakes in the codes. Could you kindly check the codes I used? I am also glad to share the raw data with you, see the link: https://www.dropbox.com/s/desthdsxsqujwga/Archive.zip?dl=0

While reading your comment more carefully, now I realize what's going on here... I am pretty sure this is an annoying issue with UMAP.. i.e. **when UMAP-transforming the same number of samples as the samples used in the model fitting, WEIRD things can happen**.. (as you noticed, the results only become non-sense if the subset is of the same size as wt data) 

I ran into the same issue in another project a while ago and it took me quite a bit of time to figure it out..

If your ko data happens to have the same number of cells as in ko data, a hacky way I used to get around this issue: 

1) manually add one more random sample/cell in the query/ko data to make ko data have a different number of cells from wt data
2)remove the artificial sample/cell and only keep the samples/cells you need **after UMAP transformation**

So you can try something like:
```python
###before mapping
adata_ko_tmp = adata_ko.concatenate(adata_wt[0,].copy(),join='outer')
adata_ko_tmp.uns = adata_ko.uns 

###mapping
adata_all = st.map_new_data(adata_wt, adata_ko_tmp)
adata_all.obs['batch'] = adata_all.obs['batch'].astype(str)
torep = {'ref': 'wt', 'new': 'ko'}
adata_all.obs['batch'] = adata_all.obs['batch'].replace(torep, regex=False)

###after mapping
adata_all = adata_all[:-1,:].copy()
```
This should work.

**Comment by ccshao** [comment]
Thanks!  The trick works nicely.
