### ISSUE TITLE
Visual genes - issue

### ISSUE THREAD

**Issue by pawelsm** [pinellolab/STREAM#11]
Hi,

I am Running your docker with stream web-application

There is apparently problem with Visual genes code.

It output the error:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/RESULTS_FOLDER/STREAM_89e7f264-cb7f-46a0-bccd-bf287d4a50dd/S5/subway_coord_Sox9.csv'

but the file is there and has content:

(base) root@90cc84aab7c2:/stream_web# head -3 /tmp/RESULTS_FOLDER/STREAM_89e7f264-cb7f-46a0-bccd-bf287d4a50dd/S5/subway_coord_sox9.csv 
	D0	D1	Sox9
AAAGCAAGTTGGTTTG	0.6992542726449995	-0.2282641959402088	0.9517325
AAAGCAAGTCAACATC	0.40922910959385095	-0.015521488506199835	0.4657253

When I change the gene name in the file name to capital sox9 ->Sox9 it is able to show the plot.
Your code is saving gene name as small letter but tried to read as capital letters.

additionally there is only subway plot and no stream plot is showing up for "Visualize Genes of Interest"
Stream plot issue is the same small vs capital letter in the name of PNG file.

best,

P.

**Comment by huidongchen** [comment]
Hi,

Can you try `docker pull pinellolab/stream_web` to get the latest version? It was due to a few bugs when we transitioned from python2 to python3. It should be fixed now.

**Comment by pawelsm** [comment]
Hi,

My version is 
pinellolab/stream_web           latest                      86286af5ec94        3 weeks ago         3.03GB
will it help to pull the new version ?
best,
P.

**Comment by huidongchen** [comment]
Yes, the one you have is the old version. If you do `docker pull pinellolab/stream_web`, it will update it automatically.

**Comment by lucapinello** [comment]
Hi @pawelsm does it work for you now?
