### ISSUE TITLE
How can I save the STREAM plot as high quality PDF file?

### ISSUE THREAD

**Issue by crazyhottommy** [pinellolab/STREAM#111]
Hi,
A quick question, after running `st.plot_stream(adata,root='S4',color=['label','CRIP1'], factor_num_win=5, dist_scale=1)`
how can I save the output as a high quality PDF? 

Thanks!

**Comment by huidongchen** [comment]
Hi Ming,

You can simply set `save_fig = True` (by default, it will be saved as pdf file although you can change the format by specifying `fig_format`)

```python
st.plot_stream(adata,root='S4',color=['label','CRIP1'], factor_num_win=5, dist_scale=1,save_fig = True)
```

**Comment by crazyhottommy** [comment]
Thanks!
