### ISSUE TITLE
value of the legend 

### ISSUE THREAD

**Issue by yxiao832** [pinellolab/STREAM#127]
Hi, 
Thanks for this great tool!
I have a question regarding the value of the legend (-5 to 15)on the very right in the following plot,
![Screen Shot 2021-09-13 at 12 24 47 PM](https://user-images.githubusercontent.com/46054827/133121513-afb1f1bf-f689-4608-b646-e73b95b1cc3b.png)

I am wondering what the value represents or how it was calculated?

Thanks!
Yang

**Comment by huidongchen** [comment]
Hi Yang,

Thanks for trying STREAM and sorry about the delay.

The values shown here are z-scores, which measure the variability of TF motifs. For more details, please check out the section "STREAM reconstructs trajectories from scATAC-seq data" in our manuscript.
