### ISSUE TITLE
detect_leaf_genes

### ISSUE THREAD

**Issue by pawelsm** [pinellolab/STREAM#14]
Dear Developers,

Got this error running your example pipeline (STREAM_scRNA-seq.ipynb) on my data.
"detect_leaf_genes" complains - index out of bound
Any suggestion how to fix it.

best,
Pawel

Minimum number of cells expressing genes: 5

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-38-d18c196abc5c> in <module>
----> 1 st.detect_leaf_genes(adata,root='S5',preference=['S2','S1'])

~/anaconda3/envs/streamEnv/lib/python3.6/site-packages/stream/core.py in detect_leaf_genes(adata, cutoff_zscore, cutoff_pvalue, percentile_expr, n_jobs, use_precomputed, root, preference)
   4409     min_num_cells = max(5,int(round(df_gene_detection.shape[0]*0.001)))
   4410     print('Minimum number of cells expressing genes: '+ str(min_num_cells))
-> 4411     input_genes_expressed = np.array(input_genes)[np.where((df_sc[input_genes]>0).sum(axis=0)>min_num_cells)[0]].tolist()
   4412     df_gene_detection[input_genes_expressed] = df_sc[input_genes_expressed].copy()
   4413 

IndexError: index 27998 is out of bounds for axis 0 with size 27998

**Comment by huidongchen** [comment]
Hi Pawel,

This error looks a bit puzzling to me. It's kind of difficult to debug without looking into the dataset. Would you mind sharing with us the minimum data that we can use to reproduce your error?

**Comment by pawelsm** [comment]
should be possible I will contact you over the email

**Comment by huidongchen** [comment]
The error was caused by the repetitive gene names stored in `adata.raw`. The easiest way to fix it is to add the following two lines after you read in the data matrix file:

```
adata.var_names_make_unique
adata.raw = adata
```
