### ISSUE TITLE
Directory error 

### ISSUE THREAD

**Issue by jhemela** [pinellolab/STREAM#16]
Hi there, 

Thank you for this wonderful resource! I am an undergraduate working in a lab over the summer. I want to analyze scRNA data from two experiments, both with DMSO and RO48 runs and each run having a genes.tsv, barcodes.tsv, and matrix.mtx file. 

Right now, I am trying to run this code; https://github.com/pinellolab/STREAM/blob/master/tutorial/1.STREAM_scRNA-seq.ipynb... ( with changing the file names to match mine)

I get stuck once I try to run the read function. I get a directory error. I have made sure I am doing the right path file and I have even tried to use the absolute path of the file, but I'm having no luck. I also tried changing the working directory, but that was unsuccessful as well. 

Any help or advice would be greatly appreciated! Thank you in advance!

**Comment by huidongchen** [comment]
Hi,
Thanks for trying STREAM. Would you mind sharing with me the code you are using to read in files and also the directory structure of your input data and script?

**Comment by jhemela** [comment]
Hi there, 

Thanks for your reply. I am trying to use this to read in files:
adata=st.read(file_name='./STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')

This is the directory structure:
/Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx

**Comment by huidongchen** [comment]
The code looks fine to me. Did you put both genes.tsv and barcodes.tsv under the same folder as 'matrix.mtx'?  Also could you tell me the output errors you saw?

**Comment by jhemela** [comment]
Yes, the genes, barcodes, and matrix files are all in the ‘DMSO’ folder.  

This is the run and output:

>>> 'exec(%matplotlib inline)'
'exec(%matplotlib inline)'
>>> import stream as st
>>> st.__version__
'0.3.9'
>>> adata=st.read(file_name='./STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/stream/core.py", line 105, in read
    adata = ad.read_mtx(_fp(file_name),**kwargs).T 
  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/anndata/readwrite/read.py", line 224, in read_mtx
    X = mmread(fspath(filename)).astype(dtype)
  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py", line 75, in mmread
    return MMFile().read(source)
  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py", line 417, in read
    stream, close_it = self._open(source)
  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py", line 317, in _open
    stream = open(filespec, mode)
FileNotFoundError: [Errno 2] No such file or directory: './STREAM/EXP1/DMSO/matrix.mtx'

and when I try to change the directory:
>>> import os
>>> os.chdir('Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx'
>>> os.chdir('Users/juju/Documents/STREAM/EXP1/DMSO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'Users/juju/Documents/STREAM/EXP1/DMSO'

**Comment by seekingseq** [comment]
I would like to be able to use the interactive website, but there is perpetual uploading when trying to upload the matrix file

**Comment by jhemela** [comment]
I'd like to run it using the interactive website, but there is perpetual uploading when I try to upload the matrix file

**Comment by jhemela** [comment]
And I am running this in a python environment from anaconda

**Comment by huidongchen** [comment]
It seems to me your file path is not correct. Where is your ipython notebook located? Is it under the folder `/Users/juju/Documents/`? If not, then you need to move jupyter notebook to `/Users/juju/Documents/`

or you can put  your `.ipynb` notebook under `/Users/juju/Documents/STREAM` and then read in files using

> adata=st.read(file_name='./EXP1/DMSO/matrix.mtx',file_format='mtx')

Since the interactive website is a simplified version of bioconda package 'stream' and is currently hosted in a small machine, to get a solid analysis, I would suggest running your analysis within Jupyter notebook.

**Comment by jhemela** [comment]
Ok! So I am using the anaconda navigator application. I go to anaconda environments and open 'myenv' environment with ipython. I am unfamiliar with how to move the jupyter notebook, but I will try to do that now.

**Comment by huidongchen** [comment]
Awesome! Let me know if re-locating your ipython notebook solves the issue.

**Comment by lucapinello** [comment]
@jhemela you can also avoid to move the notebook and provide the full path to the files you are trying to read.

For example, to load the matrix you need to change this:

adata=st.read(file_name='./STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')

into this:

adata=st.read(file_name='**Users/juju/Documents/**STREAM/EXP1/DMSO/matrix.mtx,file_format='mtx')

You need to specify the full path also for the other files.

**Comment by jhemela** [comment]
@lucapinello thank you for your suggestion! I ran the edited line and got this error: 

>>>adata=st.read(file_name='**Users/juju/Documents/**STREAM/EXP1/DMSO/matrix.mtx,file_format='mtx')
  File "<stdin>", line 1
adata=st.read(file_name='**Users/juju/Documents/**STREAM/EXP1/DMSO/matrix.mtx,file_format='mtx')
                  ^
SyntaxError: invalid syntax

**Comment by lucapinello** [comment]
you need to remove the ** (this is the symbol GitHub uses for the bold
text).

so the correct line is:

adata=st.read(file_name='Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')

**Comment by jhemela** [comment]
Thank you, but still no luck. 


In [1]: 'exec(%matplotlib inline)'                                              
Out[1]: 'exec(%matplotlib inline)'

In [2]: import stream as st                                                     

In [3]: st.__version__                                                          
Out[3]: '0.3.9'

In [4]: adata=st.read(file_name='Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')                                                                                                       
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-f821e7c4a42e> in <module>
----> 1 adata=st.read(file_name='Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')

/anaconda3/envs/myenv/lib/python3.6/site-packages/stream/core.py in read(file_name, file_path, file_format, delimiter, experiment, workdir, **kwargs)
    103             adata.raw = adata
    104         elif(file_format == 'mtx'):
--> 105             adata = ad.read_mtx(_fp(file_name),**kwargs).T
    106             adata.X = np.array(adata.X.todense())
    107             print(_fp(os.path.join(os.path.dirname(file_name),'genes.tsv')))

/anaconda3/envs/myenv/lib/python3.6/site-packages/anndata/readwrite/read.py in read_mtx(filename, dtype)
    222     from scipy.io import mmread
    223     # could be rewritten accounting for dtype to be more performant
--> 224     X = mmread(fspath(filename)).astype(dtype)
    225     from scipy.sparse import csr_matrix
    226     X = csr_matrix(X)

/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py in mmread(source)
     73         Matrix Market file.
     74     """
---> 75     return MMFile().read(source)
     76 
     77 # -----------------------------------------------------------------------------

/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py in read(self, source)
    415             Matrix Market file.
    416         """
--> 417         stream, close_it = self._open(source)
    418 
    419         try:

/anaconda3/envs/myenv/lib/python3.6/site-packages/scipy/io/mmio.py in _open(filespec, mode)
    315                     stream = bz2.BZ2File(filespec, 'rb')
    316                 else:
--> 317                     stream = open(filespec, mode)
    318 
    319             # open for writing

FileNotFoundError: [Errno 2] No such file or directory: 'Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx'

**Comment by lucapinello** [comment]
Sorry I forgot the* / *at the beginning

adata=st.read(file_name='/Users/juju/Documents/STREAM/
EXP1/DMSO/matrix.mtx',file_format='mtx')

**Comment by jhemela** [comment]
thank you so much!! it ran successfully! how do I continue onto my next line of code? 

>>>adata=st.read(file_name='/Users/juju/Documents/STREAM/EXP1/DMSO/matrix.mtx',file_format='mtx')
/Users/juju/.anaconda/navigator/a.tool: line 1: 18482 Killed: 9               /anaconda3/envs/myenv/bin/python -i
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]

how do I enter a new command? it won't let me type now

**Comment by lucapinello** [comment]
If the process get killed it means your machine doesn't have enough memory.

You need to use a machine with more memory.

This is also why probably the website was not working since it doesn't
support large datasets.
