### ISSUE TITLE
STREAM stops after "Selecting most variable genes" part with data more than 2500 cells

### ISSUE THREAD

**Issue by hkarakurt8742** [pinellolab/STREAM#17]
Hello,
I am using STREAM on Docker. Everything is looking well with data sets up to 2500 cells but when I try to use in on data sets with more than 2500 cells, it stops without any error or warning message when it selects the most variable genes.

The code I am using:
docker run  -v ${PWD}:/data -w /data  pinellolab/stream -m IM_exp_data.txt -l IM_cell_labels.tsv --clustering sc --LG --TG --DE --umap -o IM

Thank you in advance.

**Comment by lucapinello** [comment]
Try to increase the memory allocated to Docker. This should solve the
issue.

**Comment by hkarakurt8742** [comment]
It worked. Thanks a lot.
