### ISSUE TITLE
Password problem with Docker installation

### ISSUE THREAD

**Issue by Christina707** [pinellolab/STREAM#19]
When I tried the command docker pull pinellolab/stream I got an error saying "Unauthorized: incorrect username or password". Is a password needed?

**Comment by lucapinello** [comment]
Hi Christina,

No, you don't need the password unless you are trying build and push.

I just tried the pull and it works for me:

docker pull pinellolab/stream

You may have a problem with your installation of Docker or a very old
version.

I used for my test: Docker version 18.09.2, build 6247962

Thanks,

Luca
