### ISSUE TITLE
Perpetual uploading

### ISSUE THREAD

**Issue by JBreunig** [pinellolab/STREAM#2]
I'm very interested to try your pipeline for inferring cell trajectories.  However, when I upload my .tsv file, I get a perpetual "UPLOADING".  Any suggestions?

I've tried 3 different browsers and several different computers with no success.

**Comment by lucapinello** [comment]
How big is the file?

**Comment by JBreunig** [comment]
The gz file that I attempted to upload is 12,050 kb.  The uncompressed version would be 115 MB.
Thanks for the assistance!
[stream_tfp_test.tsv.gz](https://github.com/pinellolab/STREAM/files/2008562/stream_tfp_test.tsv.gz)
