### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by OpenIDUser6** [pinellolab/STREAM#21]
Hello,
Thank you for your great tool.
I ran the example successfully, which has less than 200 cells and 200 genes. however, when I tried my samples which are 6994 cells, 21029 genes, and I gave 12 thread and 12G for each thread, I got error message as:
- STREAM Single-cell Trajectory Reconstruction And Mapping -
Version 0.3.9

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Saving results in: stream_result
Input: 6994 cells, 21029 genes
No cell label file is provided, 'unknown' is used as the default cell labels
No cell color file is provided, random color is generated for each cell label
Filtering genes...
Filter genes based on min_num_cells
After filtering out low-expressed genes: 
6994 cells, 13960 genes
Removing mitochondrial genes...
remove mitochondrial genes:
['MT-ND6', 'MT-CO2', 'MT-CYB', 'MT-ND2', 'MT-ND5', 'MT-CO1', 'MT-ND3', 'MT-ND4', 'MT-ND1', 'MT-ATP6', 'MT-CO3', 'MT-ND4L', 'MT-ATP8']
Selecting most variable genes...
698 variable genes are selected
feature var_genes is being used ...
32 cpus are being used ...
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
Aborted

any help will be really appreciated.
Ting

**Comment by huidongchen** [comment]
Hi Ting,

Could you check the open issue #20 ? Basically you need to adjust the default dimension reduction method and lower the number of neighbors
