### ISSUE TITLE
No figure output when running STREAM on the cluster

### ISSUE THREAD

**Issue by zhiliu-git** [pinellolab/STREAM#25]
Hi, thanks for developing this amazing tool! I ran into some problems when trying to run the customized python script on the cluster - there is no figure output. When I ran these same python commands on a python terminal, it generated the figure just fine. It seems like when running the script on the cluster, it stopped at the figure generating step, and wouldn't give any errors. I really don't know what's going on. 

Here's my script test.py:

```
#!/usr/bin/env python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import stream as st
adata=st.read(file_name='./ExpressionMat_input.tsv')
st.filter_genes(adata,min_num_cells = max(5,int(round(adata.shape[0]*0.001))),
                min_pct_cells = None,expr_cutoff = 1)
fig = st.select_variable_genes(adata,save_fig=True,fig_name='test.png')
print("hello world")
```

Here's the error file STREAM.e1234567 :
```
/cluster/data/project
STREAM.e1234567 (END) 

```
Here's the output file STREAM.o1234567:
```
Using default working directory.
Saving results in: /cluster/data/project
Filter genes based on min_num_cells
After filtering out low-expressed genes: 
9490 cells, 11339 genes
STREAM.o1234567 (END) 
```

Here's how I submitted the script to the cluster:
`qsub -N STREAM -l mem_free=10G,h_vmem=10G -cwd test.py`

I tried to increase the memory but it still would not work. Please help. Thank you for your time! :)

**Comment by CeciiileT** [comment]
Hey
How did you solve your problem....?
Thks

**Comment by huidongchen** [comment]
> Hey
> How did you solve your problem....?
> Thks

Did your script finish? are there any other files generated except for figures?

Can you also try to specify the number of cores for the steps that enable parallel computing? 

e.g. `st.select_variable_genes(adata,loess_frac=0.01,save_fig=True,n_jobs=2)`
`st.dimension_reduction(adata,,method='se',nb_pct=50.0/adata.obs.shape[0],n_components=10,n_jobs=2)`
`st.plot_dimension_reduction(adata,save_fig=True)`
