### ISSUE TITLE
st.plot_flat_tree error

### ISSUE THREAD

**Issue by ccshao** [pinellolab/STREAM#26]
We are trying the tutorial with version 0.3.9. The stream is installed in the local machine following the suggested way.

plot_flat_tree does not work, with the following error:
```

st.plot_flat_tree(adata)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-f0350c6f5f3c> in <module>
----> 1 st.plot_flat_tree(adata)

~/miniconda3/envs/envst/lib/python3.6/site-packages/stream/core.py in plot_flat_tree(adata, adata_new, show_all_cells, save_fig, fig_path, fig_name, fig_size, fig_legend_ncol)
   1720 
   1721     flat_tree = adata.uns['flat_tree']
-> 1722     dict_nodes_pos = nx.spring_layout(flat_tree,random_state=10)
   1723     bfs_root = list(flat_tree.nodes())[0]
   1724     bfs_edges = list(nx.bfs_edges(flat_tree, bfs_root))

TypeError: fruchterman_reingold_layout() got an unexpected keyword argument 'random_state'

```

What could be the issues? Thanks!

**Comment by lucapinello** [comment]
Thanks for reporting this.

It seems this may be related to the version of networkx.

Can you please check in the env where you have stream which version of
networkx you got installed with the following commands:

# python

Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)

[GCC 7.3.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import networkx as nx

>>> nx.__version__

'2.1'


Thanks,


Luca

**Comment by ccshao** [comment]
I have a newer version of networkx
```
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import networkx as nx
>>> nx.__version__
'2.3'
```

**Comment by lucapinello** [comment]
This is what I suspected.

Did you installed STREAM with bioconda and using a new env?

Since in the recipe we specify to use version 2.1 (see here:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/stream/meta.yaml
).

If you install STREAM in an existing env this may create problems and you
will get the wrong version of networkx.

Try with a new fresh environment and this should fix your problem.

**Comment by ccshao** [comment]
I reinstalled the stream to envst2 with `conda create -n envst2 python=3.6 stream jupyter`. 
Still the python found the netowrkx 2.3
```
(base) ~ $ conda activate envst2
(envst2) ~ $ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> nx.__version__
'2.3'
>>> 
```

However, the `conda list` shows the **networkx 2.1** installed. 

```
(envst2) ~ $ conda list
# packages in environment at /home/shao/miniconda3/envs/envst2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_r-mutex                  1.0.1               anacondar_1    conda-forge
anndata                   0.6.22.post1               py_1    conda-forge
attrs                     19.1.0                     py_0    conda-forge
...
nbconvert                 5.6.0                    py36_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.1                        py_1    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
numba                     0.45.1           py36hb3f55d8_0    conda-forge
...
```

I have uninstalled the networkx 2.3 on the system level via pip.
```
(envst2) ~ $ conda deactivate
(base) ~ $ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'networkx'
>>> 

```
Now I have no idea where the networkx 2.3 locates, and why networkx is not used.

**Comment by lucapinello** [comment]
If you have mixed conda and  pip I am not sure your conda installation is
still valid (you may need to reinstall anaconda).

Also make sure you have added the right channels and their priority is
correct as documented here: http://www.ddocent.com//bioconda/

**Comment by ccshao** [comment]
Thanks for the tip, I found another python 3.6 with networkx 2.3 (by pip, a messy setting ...). Uninstalled it makes the python in evnst2 finds the correct networkx 2.1. Interestingly the conda env is not totally isolated from the system setting.

**Comment by lucapinello** [comment]
Glad you fixed the problem.

Best,

Luca
