### ISSUE TITLE
2500 cell limit

### ISSUE THREAD

**Issue by mjsteinbaugh** [pinellolab/STREAM#3]
Hi all,

I'm really enjoying STREAM and have starting pointing people over at HMS who are interested in trajectory analysis to the website. One issue that is popping up is the 2500 cell limit. Most projects at HMS are using inDrops or 10X Genomics, with at least ~3000 cells per sample, and many projects are analyzing multiple samples. Is there a way to use STREAM on larger datasets, say by running locally or with Docker in the cloud?

Best,
Mike

**Comment by lucapinello** [comment]
Hey Mike,

Thanks for trying STREAM.

Yes,  Docker would be the best way to run it with more than 2500 cells (for now). Unfortunately we have a very small server to host the website for now that is why we had to limit it.

We are in the process also to create a conda package, if you want we can send you a preliminary version as soon as we have it.

Also for each dataset analyzed and hosted (Precomputed page) we have the docker command line used, for example for the first one:

docker run -v $PWD:/data -w /data pinellolab/stream STREAM -m data_Nestorowa.tsv.gz -l cell_label.tsv.gz -c cell_label_color.tsv.gz

Hope this is helpful.

Best,

Luca

**Comment by lucapinello** [comment]
Thanks Mike! if you have any problems/suggestions don't hesitate to contact us.

**Comment by tsotnech** [comment]
Hi guys,

I'm trying to run ~2000 cells online, it's already running for 2 days and for the 1st step to compute the trajectories, but not sure if it's really running or stuck... I tried to run multiple times but calculation takes never ends. If I subset the data and run only 300 cells it turns out the trajectory plots. 
Can you recommend anything? should I wait even more and leave it running for couple of days? 

Thanks a lot

**Comment by huidongchen** [comment]
Hi 

 I m sorry about the issue. There must be something wrong during the running..  It should be fast for 2000 cells.  But its hard to tell given these information. 

We recently released a python3 version package.(conda install stream) . It’s not well documented yet but it should work much faster than the docker command line. 

I m happy to share a tutorial ipython notebook if you would like to try it.

**Comment by lucapinello** [comment]
@tsotnech the web server ran out of space. Maybe this explains your problem. Please try again online, but the new python3 package is way better. So I will suggest the solution proposed by @huidongchen

**Comment by tsotnech** [comment]
Thanks a lot for the suggestions, @huidongchen I'll be happy to try new Python3 package.

**Comment by huidongchen** [comment]
@tsotnech  Please find attached the dropbox link, where the tutorial script and datasets are included. There are still a few small bugs we need to fix but the core functions are already there.
 Hope the ipython notebook will be helpful. Please feel free to let us know if you have any questions.
 
https://www.dropbox.com/sh/bx6mnndxgy9tus0/AABs5zWjSBKZa635hSwysKrSa?dl=0
