### ISSUE TITLE
No 'se' method in the 'map_new_data' function

### ISSUE THREAD

**Issue by jipeifeng** [pinellolab/STREAM#32]
HI:
     Thank you for developing this  powerful tool. I'm using its 'map_new_data' function, the former data set I used for dimension  reduction is 'se' (large scale data set). But when I mapping the new data set to the former one, I found that no 'se' option was provided. Thank you !

**Comment by huidongchen** [comment]
Hi 
This is related to #28 . Unfortunately in the current version we don't support 'se' yet. But we will add it in the upcoming new version. Stay tuned!

**Comment by huidongchen** [comment]
Sorry about the long waiting! Now `se` is now supported in `stream v0.4.0`
