### ISSUE TITLE
exchange head and tail

### ISSUE THREAD

**Issue by ateissan** [pinellolab/STREAM#36]
Hello, 

I have a linear trajectory. And I would like to exchange head and tail of the trajectory. How can I do that?
Thanks,
Aurélie

**Comment by lucapinello** [comment]
Hi Aurélie,

You just need to specify the root node.

For example, to generate a stream plot with root S4 you will write:

st.stream_plot(adata,*root='S4'*,fig_legend_ncol=6,fig_size=(8,8),factor_min_win=1.2,preference=['S2','S1'])


Best,

Luca
