### ISSUE TITLE
Issue with elastic_principal_graph

### ISSUE THREAD

**Issue by lvlahos343** [pinellolab/STREAM#42]
When I run this function (following the single-cell tutorial), my environment seems ot be missing the stringi.so library. I'm not sure if this is an issue with the instructions in the tutorial - which I've followed to the letter - of with my own system. However, I've been unable to find any other solutions to this specific problem in other contexts, and was hoping some user or dev might have insight into a work around.

**Comment by huidongchen** [comment]
Can you try `Rscript -e 'install.packages("stringi",repos="https://cloud.r-project.org/")'` in your terminal? this should fix the problem.

**Comment by JSchapke** [comment]
> Can you try `Rscript -e 'install.packages("stringi",repos="https://cloud.r-project.org/")'` in your terminal (within your env)? this should fix the problem.

Great! It fixed my problem.
