### ISSUE TITLE
controlling the extention in extend_elastic_principal_graph

### ISSUE THREAD

**Issue by ccshao** [pinellolab/STREAM#43]
Dear Stream team, 

Sorry to bother you again but I have some difficulties in tuning the parameter of `st.extend_elastic_principal_graph`.

The principle graph likes this. 

![Screenshot from 2019-11-26 14-24-28](https://user-images.githubusercontent.com/4980631/69646655-7ee80700-1068-11ea-9d98-329ffa11456d.png)

While produce a needle structure in the stream plots.
![Screenshot from 2019-11-26 16-15-13](https://user-images.githubusercontent.com/4980631/69646677-86a7ab80-1068-11ea-9c9c-b390642c8627.png)

You might noticed that the extreme blue dots in the S1 are far away from the leaf. I hope to control cells that are further included in the graph, or to make them a little bit closer to the leaf.

**Firstly**, am I correct to use the `extend_elastic_principal_graph` for that purpose? or is it possible at all? 

I tried a few option, 
```
#- option 1
st.extend_elastic_principal_graph(adata)
st.plot_branches_with_cells(adata, n_components=2, save_fig=True, fig_name='extended_branches_cells.pdf')

#- option 2
st.extend_elastic_principal_graph(adata, epg_ext_par=0.01)
st.plot_branches_with_cells(adata, n_components=2, save_fig=True, fig_name='extended_branches_cells_2.pdf')

#- option 3
st.extend_elastic_principal_graph(adata, epg_ext_par=0.99)
st.plot_branches_with_cells(adata, n_components=2, save_fig=True, fig_name='extended_branches_cells_3.pdf')

```

The pseudotime and stream plots are nearly identical.

Further, I have tried epg_trimmingradius and epg_ext_mode as well but couldn't see a clear difference. I guess I might misunderstand the command. Could you kindly explain the function a little bit more?

Thanks very much!

**Comment by huidongchen** [comment]
Hmmm, I don't see anything wrong in your command. Increasing `epg_ext_par ` should help read further points. This can be clearly illustrated in [1.1.STREAM_scRNA-seq (on 2D plane).ipynb](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.1.STREAM_scRNA-seq%20%28on%202D%20plane%29.ipynb?flush_cache=true). Could you share a minimal test dataset so that i can help test it on my side as well?

**Comment by ccshao** [comment]
Thanks for the quick reply and the effor in making new release. I installed the 0.4 version under python3.6, however, the run of tutorial failed at the steps of `st.optimize_branching(adata)`, with the error likes:

> Optimizing branching...
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-15-9441cfc2c7e4> in <module>
>       1 ### optional step
> ----> 2 st.optimize_branching(adata)
>       3 # st.plot_branches(adata)
>       4 # st.plot_branches_with_cells(adata)
> 
> ~/miniconda3/envs/env_st_0_4/lib/python3.6/site-packages/stream/core.py in optimize_branching(adata, incr_n_nodes, epg_maxsteps, mode, epg_lambda, epg_mu, epg_trimmingradius, epg_finalenergy, epg_alpha, epg_beta, epg_n_processes, reset, **kwargs)
>    1551         epg = adata.uns['ori_epg']
>    1552     else:
> -> 1553         epg_obj = adata.uns['epg_obj']
>    1554         epg = adata.uns['epg']
>    1555     if(len(extract_branches(epg))<3):
> 
> KeyError: 'epg_obj'
> 

Indeed there is no `epg_obj` in the `adata.uns`. Did I miss some steps?

> 
> {'experiment': 'rna-seq',
>  'workdir': './stream_result',
>  'label_color': {'MPP': '#eea113',
>   'HSC': '#40bdbd',
>   'GMP': '#10b460',
>   'CMP': '#d84f40',
>   'MEP': '#286ee1'},
>  'var_genes': Index(['Mns1', 'Fam107b', 'Atp1b2', '9030619P08Rik', 'Prtn3', 'Gmnn', 'Memo1',
>         'Cdkn1c', 'Gm2a', 'Nudt19',
>         ...
>         'Gm15915', 'Abhd4', 'Metap2', 'Irak3', 'Myct1', 'Lsp1', 'Tyrobp',
>         'Nkg7', 'C330018D20Rik', 'Rnf125'],
>        dtype='object', length=476),
>  'trans_se': SpectralEmbedding(affinity='nearest_neighbors', eigen_solver=None, gamma=None,
>                    n_components=2, n_jobs=16, n_neighbors=100, random_state=10),
>  'epg': <networkx.classes.graph.Graph at 0x7fa50cec2668>,
>  'flat_tree': <networkx.classes.graph.Graph at 0x7fa523520048>,
>  'seed_epg': <networkx.classes.graph.Graph at 0x7fa523520c88>,
>  'seed_flat_tree': <networkx.classes.graph.Graph at 0x7fa5235203c8>}
>

**Comment by huidongchen** [comment]
Did you run this step `st.elastic_principal_graph(adata)`? I tried the tutorial again. Everything seems to work fine for me.

**Comment by ccshao** [comment]
Yes you are right, the `elastic_principal_graph` step didn't finished correctly. The output was long and I forgot to check the bottom. The `stringi` packeage could not be loaded due to a error:

> libicui18n.so.64: cannot open shared object file: No such file or directory

Solved by re-install `stringi` under the conda environment.

Back to original question, the alignment looks much better if the data to be mapped is normalized by stream beforehand, which is mentioned in the methods part of paper.
