### ISSUE TITLE
Issues adding labels and colours

### ISSUE THREAD

**Issue by valie15** [pinellolab/STREAM#44]
I'm sorry, I'm having a very basic issue and for the life of me can not resolve it. This is what I run:

```
adata = st.read(file_name= 'stem.txt', workdir= './Stream')
adata
```
The above is my count file.
Then I pass :

```
st.add_cell_colors(adata, file_name = 'simplecolour.txt')
st.add_cell_labels(adata, file_name = 'lineage.txt')
```

Where 'simplecolour' is a text file (no headers) where column 1 is the name of the cells as they appear in the count file, and column two is the colour that that cell should have (I've used hex codes).

'lineage' is again all the cells, as named in the count file in column 1 and in column 2 is their appropriate lineage. These two commands passed together throw the following error : 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'label'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-252-a08df3834e60> in <module>
----> 1 st.add_cell_colors(adata, file_name = 'simplecolour.txt')
      2 st.add_cell_labels(adata, file_name = 'lineage.txt')

~/anaconda3/lib/python3.7/site-packages/stream/core.py in add_cell_colors(adata, file_path, file_name)
    289 
    290     _fp = lambda f:  os.path.join(file_path,f)
--> 291     labels_unique = adata.obs['label'].unique()
    292     if(file_name!=None):
    293         df_colors = pd.read_csv(_fp(file_name),sep='\t',header=None,index_col=None,names=['label','color'],

~/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2993             if self.columns.nlevels > 1:
   2994                 return self._getitem_multilevel(key)
-> 2995             indexer = self.columns.get_loc(key)
   2996             if is_integer(indexer):
   2997                 indexer = [indexer]

~/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897                 return self._engine.get_loc(key)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2901         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'label'
```

I'm sorry if im being dumb. I tried doing the obvious thing of adding in the header for the appropriate column as 'label' and 'label_color' but that hasnt worked either.
Would anyone have a suggestion? or be able to share even a screenshot of how they present their data so I can replicate it?
 Thanks

**Comment by huidongchen** [comment]
Can you try to switch these two steps, i.e. adding labels before adding colors (Since the colors are dependent on  labels, labels should always be added first):

```
st.add_cell_labels(adata, file_name = 'lineage.txt')
st.add_cell_colors(adata, file_name = 'simplecolour.txt')
```
There are several example files you can check here [example files](https://www.dropbox.com/sh/dfqht1ob89ku99d/AACI5ZW3aRuq9MhBfSNS_1O_a?dl=0)

**Comment by valie15** [comment]
Thank you for this, I've downloaded the files you've sent (thanks! really helps).
Just to clarify something as I'm slightly confused :

so the colors file obviously goes into the add_cell_color section, for the labels, I assume you use the "cell_label.tsv", in your example. In this though I am not seeing any of the cell names next to it. Does that mean that for labels you simply just add the labels in the order your "cell names/ barcodes" run in the "data" folder?

**Comment by huidongchen** [comment]
> Does that mean that for labels you simply just add the labels in the order your "cell names/ barcodes" run in the "data" folder?

Yes, the label file simply contains the labels in the order of cell names/barcodes. https://github.com/pinellolab/STREAM#input-file-format

In the latest `stream v0.4.0`, as [the tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.1.STREAM_scRNA-seq%20%28on%202D%20plane%29.ipynb?flush_cache=true) shows, it's now able to merge these two steps into one and supports adding one single metadata file: `st.add_metadata(adata,file_name='./metadata_subset.tsv')
`

**Comment by valie15** [comment]
Thank you so much for the clarification. This is immensely helpful.
Cheers for the links.
