### ISSUE TITLE
Issue when saving output from jupyterlab

### ISSUE THREAD

**Issue by valie15** [pinellolab/STREAM#45]
Hello,

When using functions such as :

`st.stream_plot_gene(adata,root='S0',fig_size=(8,8),genes=['Notch1', 'Notch2', 'Notch3']) 
`

to plot a list of our favorite genes, is there a way for the plot to be saved directly into the directory by amending the above code?
Alternatively would you know a way to do this to save the image as possibly an .svg or any other format? When saving image as is used it only saves the first gene in the plot.
Thanks

**Comment by huidongchen** [comment]
Yes, you can simply specify `save_fig=True` and `fig_format='pdf'`. This will save your gene plots as pdf files under the folder `S0`.

You can check more details of other parameters by executing `st.stream_plot_gene?`
