### ISSUE TITLE
Error with dimension_reduction

### ISSUE THREAD

**Issue by jipeifeng** [pinellolab/STREAM#46]
Hi Stream team:
            Thank your for developing this tool.
            Currently, I am using the latest version of stream (0.4.0). My data set has about 8w cells and 17,971 genes. When I run the dimension_reduction step with the following command: stream.dimension_reduction(wt, n_components=10, nb_pct=0.025, n_jobs=4), then after a long time, error happens. 

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-11-7d131990ab63> in <module>
----> 1 stream.dimension_reduction(wt, n_components=10, nb_pct=0.025, n_jobs=4)

/miniconda3/envs/stream/lib/python3.7/site-packages/stream/core.py in dimension_reduction(adata, n_neighbors, nb_pct, n_components, n_jobs, feature, method, eigen_solver)
    736                                          n_jobs = n_jobs,
    737                                          eigen_solver = eigen_solver,random_state=10)
--> 738         trans = reducer.fit(input_data)
    739         adata.uns['trans_se'] = trans
    740         adata.obsm['X_se'] = trans.embedding_

/miniconda3/envs/stream/lib/python3.7/site-packages/sklearn/manifold/_spectral_embedding.py in fit(self, X, y)
    554                                              n_components=self.n_components,
    555                                              eigen_solver=self.eigen_solver,
--> 556                                              random_state=random_state)
    557         return self
    558 

/miniconda3/envs/stream/lib/python3.7/site-packages/sklearn/manifold/_spectral_embedding.py in spectral_embedding(adjacency, n_components, eigen_solver, random_state, eigen_tol, norm_laplacian, drop_first)
    270             _, diffusion_map = eigsh(
    271                 laplacian, k=n_components, sigma=1.0, which='LM',
--> 272                 tol=eigen_tol, v0=v0)
    273             embedding = diffusion_map.T[n_components::-1]
    274             if norm_laplacian:

/miniconda3/envs/stream/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
   1626             if OPinv is None:
   1627                 Minv_matvec = get_OPinv_matvec(A, M, sigma,
-> 1628                                                hermitian=True, tol=tol)
   1629             else:
   1630                 OPinv = _aslinearoperator_with_dtype(OPinv)

/miniconda3/envs/stream/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in get_OPinv_matvec(A, M, sigma, hermitian, tol)
   1063             A = A - sigma * eye(A.shape[0])
   1064             A = _fast_spmatrix_to_csc(A, hermitian=hermitian)
-> 1065             return SpLuInv(A).matvec
   1066         else:
   1067             return IterOpInv(_aslinearoperator_with_dtype(A),

/miniconda3/envs/stream/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in __init__(self, M)
    906     """
    907     def __init__(self, M):
--> 908         self.M_lu = splu(M)
    909         self.shape = M.shape
    910         self.dtype = M.dtype

/miniconda3/envs/stream/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py in splu(A, permc_spec, diag_pivot_thresh, relax, panel_size, options)
    309         _options.update(options)
    310     return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
--> 311                           ilu=False, options=_options)
    312 
    313 

SystemError: gstrf was called with invalid arguments

Could you help me with my issue?

Best, 
Peifeng

**Comment by jipeifeng** [comment]
By the way, I'd better paste all of the commands:
1. wt = sc.read_h5ad('wt.h5ad') # the dataset was generated by scanty
2. stream.set_workdir(wt, './stream')
3. stream.remove_mt_genes(wt)
4. wt.obs.rename(columns={'type':'label'}, inplace=True) # I set the label myself
5. stream.add_cell_colors(wt)
6. stream.select_variable_genes(wt,loess_frac=0.01)
7. stream.dimension_reduction(wt, n_components=10, nb_pct=0.025, n_jobs=4) # error happens

Thank you!

**Comment by huidongchen** [comment]
Hi Peifeng,

Thanks for trying STREAM! It seems to me the error is related to the lack of memory. Instead of using ` nb_pct=0.025`, can you replace it with `n_neighbors = 100` and try it again? (8w * 0.025 = 2000 neighbor cells will require massive computing resources. Setting `n_neighbors = 100` should dramatically alleviate the intensive computation.

**Comment by jipeifeng** [comment]
Thanks for the reply. 
After reseting the parameter provided, the function works fine. But it takes a very long time to run.
