### ISSUE TITLE
Quantified density for each cell type

### ISSUE THREAD

**Issue by jipeifeng** [pinellolab/STREAM#47]
Hi:

   I see the subway or stream map could draw the change of every cell type along the pesudotime.  
   I'm wondering if it can draw the quantified density changes of each cell type. Like the results bellow? 

Thank you!
<img width="407" alt="result" src="https://user-images.githubusercontent.com/24560774/70201713-6657ab00-1752-11ea-8ace-f8295ef3d7a6.png">

**Comment by huidongchen** [comment]
stream plot is designed to represent **relative cell density** using the width of branch. Currently there is no direct way to draw quantitative density plots in STREAM package but as long as you have the pseudotime information stored in `adata.obs` it should be trivial to make such plots
