### ISSUE TITLE
Failure to generate a plot after dimensionality reduction

### ISSUE THREAD

**Issue by saramasa22** [pinellolab/STREAM#57]
Hi,

I really like the graphic of this package and the function it has so I wanted to apply it to data that I already had in tsv format (count matrix). 
Here some questions to help me better understand how it works:

1) Why is the data transposed when it's uploaded with stream? my original matrix is genes(rows), reads (columns), here is the opposite.

2) After having uploaded the data, filtered it and checked the two curves (blue and red), I couldn't plot the results of the dimensionality reduction getting an error I don't quite understand.. (screenshot)

<img width="1440" alt="Screenshot 2020-01-14 at 16 48 08" src="https://user-images.githubusercontent.com/55786246/72365805-da418780-36f0-11ea-85f1-0df926b306b7.png">

<img width="1440" alt="Screenshot 2020-01-14 at 16 48 25" src="https://user-images.githubusercontent.com/55786246/72365818-e0376880-36f0-11ea-82f9-d08760a307a5.png">

What could be the problem?
(I am a newbie in Bioinformatics so any elucidations would be great to me!)

Sara

**Comment by huidongchen** [comment]
Hi Sara,

Thanks for your interest in our tool STREAM! Re your questions:

>Why is the data transposed when it's uploaded with stream? my original matrix is genes(rows), reads (columns), here is the opposite.

STREAM is written based on a popular structure `AnnData`([Details on AnnData structure](https://icb-anndata.readthedocs-hosted.com/en/latest/index.html)), in which they store cells as observations (rows) and genes as variables (columns). So we internally transpose matrix to make STREAM analysis compatible with AnnData structure.

>After having uploaded the data, filtered it and checked the two curves (blue and red), I couldn't plot the results of the dimensionality reduction getting an error I don't quite understand.. (screenshot)

To me it seems you have not run the step `st.dimension_reduction()` yet.

**Comment by saramasa22** [comment]
Thank you very much for the explanation! I also did not specify the number of components, that's why it probably did not work.
