### ISSUE TITLE
Compatibility with singularity

### ISSUE THREAD

**Issue by lynnoyoung** [pinellolab/STREAM#6]
Hi,

Thank you for STREAM.

For our government computer we have to run singularity instead of docker.  It reads docker files, but pull is only supported for shub URI http://singularity.lbl.gov/singularity-tutorial 

Would you be willing to provide an alternative for us to get the docker image?
Setting up the shub URI seems to be automated, http://singularity.lbl.gov/singularity-tutorial 

Warm regards,
Lynn

**Comment by lucapinello** [comment]
This is a great suggestion, we can definitively try to build a singularity image. This is something novel for us so it may take some time. Alternatively, if you are already familiar with the technology you could create one since we share the source Docker file.

**Comment by lynnoyoung** [comment]
Thank you Luca,


Our High Performance Computing staff took charge:


https://hpc.nih.gov/apps/STREAM.html


Warm regards,

Lynn

Lynn Young, PhD | Bioinformatics Scientist | National Institutes of Health Library | Office of Research Services | Building 10, Room 1L13F | 10 Center Drive | Bethesda, Maryland 20892-1150 | T. 301-827-3838 | E. lynny@mail.nih.gov<mailto:lynny@mail.nih.gov> | Twitter: https://twitter.com/bioinformatics1

Stay connected with the NIH Library
NIH Library:  http://nihlibrary.nih.gov<http://nihlibrary.nih.gov/> | Facebook:  http://www.facebook.com/nihlibrary | Twitter:  <http://www.twitter.com/nihlib> http://www.twitter.com/nihlib



________________________________

**Comment by lucapinello** [comment]
Thanks a lot for the update Lynn!

Happy they were able to install it for you. It seems they didn't use
singularity right?

**Comment by lucapinello** [comment]
Hi Lynn,

Very elegant solution, can you check if they are willing to share their
conf files for using singularity with  STREAM?

Since this could benefit many other users!

Thanks again for your feedback.

Best,

Luca

**Comment by lucapinello** [comment]
Hi @lynnoyoung  we have a new and improved version od STREAM! 

We were wondering if you are willing to build a share a singularity image with us if you are updating it. Thanks!
