### ISSUE TITLE
Issues with Selecting Variable Genes

### ISSUE THREAD

**Issue by Olivia117** [pinellolab/STREAM#60]
Hello!
Thanks for this wonderful pseudotime tool. Being a first time user, I am having difficulties in selecting variable genes using st.select_variable_genes() function. I am reading an anndata (.h5ad file generated by Scanpy) as input. 

It says: IndexError: tuple index out of range

Thanks in advance,
Olivia

**Comment by jipeifeng** [comment]
Hi, it can be resolved by anndata.X = anndata.X.toarray(). This issue was caused by the format of expression matrix
