### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by abeaude** [pinellolab/STREAM#64]
I installed stream in its own conda environment : 
`conda create -n stream -c bioconda python stream jupyter`

Then I launched a jupyter notebook from this environment and started my analysis. But While I'm executing the function `st.elastic_principal_graph(adata)`, I get the following error : 
```
unable to load shared object '/opt/conda/envs/stream/R/library/stringi/libs/stringi.so':
libicui18n.so.64 cannot open shared object file no such file or directory
```
I also try to load the `stringi` library from a R notebook within the same conda environment and get the same error. 

I did some research and found [this](https://github.com/jupyter/docker-stacks/issues/927#issuecomment-583807803) which might be related to my problem. 

By looking at the comment cited above I created a new conda environment with `r 3.6.2` and loaded the `stringi` library without error. 

But I tried to install stream with `R 3.6.2` inside a conda environment without any success. I looked at the dependencies but did not find any reasons to install `R 3.6.1` and not `R 3.6.2`

Thanks for your help.

**Comment by huidongchen** [comment]
I guess this is relevant to the previous issue #42

**Comment by abeaude** [comment]
Yes definitely, 
Sorry I missed this issue
Thanks
