### ISSUE TITLE
Is there a way to know the progression of a cell along a branch ? 

### ISSUE THREAD

**Issue by abeaude** [pinellolab/STREAM#65]
Hi, 

I would like to know if it is possible to know the progression of cells along a branch. In other words, if I took a cell projected on a branch (from `adata.obs['branch_id']`), can I know the progression on the branche, a value that indicates at which percentage of the edge length the point is being projected. 

Does it correspond to `adata.obs['branch_lam']` ? 

Thanks in advance for your answer

**Comment by huidongchen** [comment]
Hi,

Sorry about the confusion. But, you are right. 

For a specific branch, `'branch_lam'` indicates the length from start node to the location onto which a cell is projected along the branch. The start node can be inferred from `branch_id`(the first node is the start node). e.g. if the `branch_id` is `(S3,S2)`, the start node is `S3`.

Hope the above is helpful to you.

**Comment by abeaude** [comment]
Thanks ! 

It's really helpful. I think I finally obtained what I wanted. 
I divided `branch_lam` by the length of the corresponding edge which I found in `adata.uns['flat_tree'][start][end]['len']`. 

Again thanks for your help
