### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by ahmedabbas81** [pinellolab/STREAM#67]
Hello,

How long does it take to finish a scATAC-seq library having around 5200 cells?

It ran since yesterday using k-mer, k=7 and did not finish. How many CPUs should I assign to job? Should I use GPU? should I use motifs faster? And are motifs accurate enough?

Thanks

**Comment by huidongchen** [comment]
Repeated issue https://github.com/pinellolab/STREAM_atac/issues/2.  

Closed.
