### ISSUE TITLE
Getting "MemoryError" when running large data sets

### ISSUE THREAD

**Issue by efheuston** [pinellolab/STREAM#7]
Hi STREAM team!--

I was very excited to see your new pipeline, and couldn't wait to try it!  

I am running an analysis on ~37500 cells. When I tried running the docker image on my desktop, the program would create several empty files and fail without error. However, it would work if I ran a smaller dataset. I moved to our high performance cluster, but because it doesn't allow docker image files I copied the contents of STREAM-master and have been running STREAM.py. The program runs through dimensional reduction and stops.

>Loading input data...
Input: 37501 cells, 17125 genes
remove mitochondrial genes:
['mt-Nd1', 'mt-Nd2', 'mt-Co1', 'mt-Co2', 'mt-Atp8', 'mt-Atp6', 'mt-Co3', 'mt-Nd3', 'mt-Nd4l', 'mt-Nd4', 'mt-Nd5', 'mt-Nd6', 'mt-Cytb']
Filtering genes...
After filtering out low-expressed genes: 
37501 cells, 13754 genes
Selecting features...
688 variable genes are selected
Number of CPUs being used: 64
Reducing dimension...
Traceback (most recent call last):
  File "STREAM.py", line 4035, in <module>
    main()
  File "STREAM.py", line 3949, in main
    X = Dimension_Reduction(df_sc_final,lle_n_component,lle_n_nb_percent,file_path,file_path_precomp,n_processes)
  File "STREAM.py", line 388, in Dimension_Reduction
    sklearn_lle = sklearn_lle.fit(DR_input_values)
  File "/data/conda/envs/stream/lib/python2.7/site-packages/sklearn/manifold/locally_linear.py", line 661, in fit
    self._fit_transform(X)
  File "/data/conda/envs/stream/lib/python2.7/site-packages/sklearn/manifold/locally_linear.py", line 645, in _fit_transform
    random_state=random_state, reg=self.reg, n_jobs=self.n_jobs)
  File "/data/conda/envs/stream/lib/python2.7/site-packages/sklearn/manifold/locally_linear.py", line 385, in locally_linear_embedding
    V = np.zeros((N, n_neighbors, n_neighbors))
MemoryError

I am currently running with 250g memory and 32 CPUs. Do I need to allocate more memory, or is there something else you would recommend.

Thanks for your advice!

E

**Comment by lucapinello** [comment]
Hello!

Thanks for trying STREAM.

This is a very big dataset :) the problem is that it doesn't fit in the
memory of your machine.

Unfortunately, with the current version you need to increase the memory,
however, we may need in the near future implement a version that is memory
efficient. In that case, we will send you a message so you could try again.

Best,

Luca

**Comment by efheuston** [comment]
Hi Luca--

 Thanks so much! I will try assigning more memory to see if that helps.

I look forward to playing with future versions of STEAM!

E

**Comment by panxiaoguang** [comment]
hello,my cell number is 90000+,if I use the new version of this software,how many memory I should use

**Comment by lucapinello** [comment]
It is hard to say, but the memory requirements for the LLE step is
quadratic on the number of cells times the number of neighbors .
Try to replace the LLE with the spectral embedding, this can save you some
memory.

**Comment by huidongchen** [comment]
I just wanted to add one comment, in the latest version `v0.4.1`, the default dimension reduction method is `se` (spectral embedding) and the default number of neighbors is 50. That being so, the latest version with default setting should be scalable enough. The only thing you might be aware of is that the sparse matrix is converted into dense matrix internally in STREAM for the sake of comparability with other dependencies. That part would be memory consuming.  I have tested dataset of similar size (we have 1T RAM) it works fine.
