### ISSUE TITLE
result of conda info stream=1.0 is empty

### ISSUE THREAD

**Issue by cb4github** [pinellolab/STREAM#74]
Dear All,

stream=1.0 doesn't seem to be available from the [indicated channels](https://github.com/pinellolab/STREAM#installation-with-bioconda-recommended).

Please advise, and please let me know if I can provide more info,

Best,
CB

**Comment by huidongchen** [comment]
Hi,

Thanks for trying STREAM. Our package is still being tested in bioconda system at the moment (It was delayed for one day due to their recent R migration and there are a few technical issues going on on their end now). But it should be ready very soon. Stay tuned. Sorry about the inconvenience.

**Comment by huidongchen** [comment]
STREAM `v1.0` is available in Bioconda channel now
