### ISSUE TITLE
problem on visualizing gene

### ISSUE THREAD

**Issue by OpenIDUser6** [pinellolab/STREAM#8]
Hello,
I am running STREAM on command line, here is the command: 
stream -m 1_Fresh_anno2TR.tsv -l 1_Fresh_cell_lable.tsv -c 1_Fresh_cell_label_color.tsv -g INS,HADH,PCSK1,NKX6-1,G6PC2 -s all -o test2

Visulizing genes...
Traceback (most recent call last):
  File "/STREAM/STREAM.py", line 4033, in <module>
    main()
  File "/STREAM/STREAM.py", line 4029, in main
    Stream_Plot_Gene(df_rooted_tree,df_sc,flat_tree,dict_branches,node_start,dict_node_state,gene_list,flag_stream_log_view,flag_atac,file_path,flag_web)
  File "/STREAM/STREAM.py", line 2847, in Stream_Plot_Gene
    max_gene_values = np.percentile(gene_values[gene_values>0],90)
  File "/opt/conda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4291, in percentile
    interpolation=interpolation)
  File "/opt/conda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
    r = func(a, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4405, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 159, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

It will be greatly appreciated if anyone could give me a clue.
Best regards,
Ting

**Comment by huidongchen** [comment]
Hi Ting,

It looks like some genes are not expressed in any cell. Can you double check these genes' expression values?

Best,
Huidong

**Comment by OpenIDUser6** [comment]
Hi Huidong,
Thank you for your reply!
I checked they do have expression data, maybe low. The data start with 16000 gene, but after the STREAM did calculation and removed low-expression genes, there are around 4000 genes left. I guess some of my interested genes are not in the 4000 gene list. what do you think?
Thanks,
Ting

**Comment by huidongchen** [comment]
Hi Ting,

When STREAM plots genes, it uses the original gene expression matrix( by default it DOES filter out genes that are expressed in less than 5 cells. But this shouldn’t remove genes massively ) 

As long as these genes are expressed in more than 5 cells, they should be plottable. 

Another thing I noticed is that in your command you are running the analysis using all genes ‘-s all’. , which is not appropriate for scRNA-seq. Can you remove the parameter ‘-s all’ and retry it? (By default it will use LOESS to select the most variable genes) 

Meanwhile , we recently developed bioconda package stream ( you can install it by ‘conda install stream’ ) . It’s not well documented yet but it’s much more flexible and is able to handle large data much better. If you are interested, I can also share with you a self-explanatory tutorial script. 

Huidong

**Comment by OpenIDUser6** [comment]
Hi Huidong,
I tried without "-s all", I got the same error message.
Thanks,
Tingfen

**Comment by huidongchen** [comment]
Hi Ting,

I'm attaching the dropbox link here. https://www.dropbox.com/sh/bx6mnndxgy9tus0/AABs5zWjSBKZa635hSwysKrSa?dl=0 

Sorry about the error. Did you check how many cells are expressing those genes you were mentioning? Is the number of cells greater than 5?
