### ISSUE TITLE
Is it possible to add more than one label at a time with STREAM?

### ISSUE THREAD

**Issue by smk5g5** [pinellolab/STREAM#80]
I am trying to visualize STREAM results with respect to cell type, Sample type and/or Seurat clusters they fall in. From the tutorial I am unable to find a way to add more than one way to color the STREAM results. Is it possible to color the STREAM plots with more than one type of coloring scheme (like Sample/Cell type/seurat expression clusters) or do I have to run each of them individually?

Thanks!

**Comment by huidongchen** [comment]
Yeah, it can be easily done in the latest version `v1.0`. Please check out our latest [tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.2.STREAM_scRNA-seq%20%28Multifurcation%29.ipynb?flush_cache=true). 

In short, all you need to do is:

1. add your metadata file `st.add_metadata(adata,file_name='./metadata.tsv')`
2. specify the parameter `color` in any plotting function you wanna try, e.g. `st.plot_stream(adata,root='S1',color=['label','sample','seraut_cluster','cell_type'])`

**Comment by smk5g5** [comment]
Ohh. Thanks for the prompt reply.

So the metadata file should contain all the different types of labels.

**Comment by huidongchen** [comment]
> Ohh. Thanks for the prompt reply.
> 
> So the metadata file should contain all the different types of labels.

Correct! 

You can specify these two columns `label` and `label_color` in your metadata file, which will be equivalent to these two steps
```
st.add_cell_labels(adata,file_name='./cell_label.tsv.gz')
st.add_cell_colors(adata,file_name='./cell_label_color.tsv.gz')
```
but it's optional. if neither of them is specified in your metadata file, `label` will all be automatically set to `unknown` and `label_color` will be set to `gray`

but you can always replace the `label` column with other annotations later by e.g. `adata.obs['label'] = adata.obs['cell_type']`
