### ISSUE TITLE
When visualizing the Seurat Clusters I am not getting the correct output even though I have converted the seurat clusters pandas column to string.

### ISSUE THREAD

**Issue by smk5g5** [pinellolab/STREAM#82]
Hi,

As per our conversation yesterday I was able to use the multi-label list  as described in the issue here https://github.com/pinellolab/STREAM/issues/80. For the seurat clusters which look as shown in the figure below. 
<img width="1128" alt="Screen Shot 2020-06-30 at 9 33 16 AM" src="https://user-images.githubusercontent.com/6811915/86140018-03df4700-bab6-11ea-9a14-c6817902b637.png">

At first STREAM was interpreting the `Seurat_clusters` cluster column as integer  and was plotting a continuous distribution over the clusters 
![image](https://user-images.githubusercontent.com/6811915/86140568-9aac0380-bab6-11ea-96da-cb9502f74193.png)

 so I changed it to str and now it is giving me a plot which does not have all cluster info. 

![image](https://user-images.githubusercontent.com/6811915/86140355-633d5700-bab6-11ea-8a05-8b5c0bef5eb1.png)

Is there a workaround to getting it right?

Thanks!

**Comment by huidongchen** [comment]
This is a notorious issue of `seaborn` package, which is used internally by STREAM. Somehow it always interprets integers as `numerical` type regardless of its real data type.

An easy workaround is to add a prefix to your cluster labels, e.g.
`adata.obs['Seruat_clusters'] = 'cluster_'+adata.obs['Seruat_clusters']`

**Comment by smk5g5** [comment]
![test_clust](https://user-images.githubusercontent.com/6811915/86144506-5e2ed680-babb-11ea-83d2-2aa5c0e1018c.png)

Is a more divergent color scheme possible here?

**Comment by huidongchen** [comment]
This is not what it's supposed to look like. Can you try to add a prefix to your cluster label as i suggested above?

**Comment by smk5g5** [comment]
That throws an error.
adata.obs['Seruat_clusters'] = 'cluster_'+adata.obs['Seruat_clusters']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/envs/env_stream/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Seruat_clusters'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-116-63bbc01b09c6> in <module>
----> 1 adata.obs['Seruat_clusters'] = 'cluster_'+adata.obs['Seruat_clusters']

~/opt/anaconda3/envs/env_stream/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2798             if self.columns.nlevels > 1:
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):
   2802                 indexer = [indexer]

~/opt/anaconda3/envs/env_stream/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Seruat_clusters'

**Comment by huidongchen** [comment]
Sorry i misspelled it. `adata.obs['Seurat_clusters'] = 'cluster_'+adata.obs['Seurat_clusters']` should work. (Please make sure the data type of `'Seurat_clusters'` is `str` first. )

**Comment by smk5g5** [comment]
Thanks! that worked great!
![test_clust](https://user-images.githubusercontent.com/6811915/86146654-1fe6e680-babe-11ea-9793-295e01221ba5.png)
