### ISSUE TITLE
Attributes interpretation 

### ISSUE THREAD

**Issue by MingBit** [pinellolab/STREAM#84]
Hallo,

Thanks for the great tool! 
I'm still new to STREAM and doing the first analysis according to [this tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.1.STREAM_scRNA-seq%20%28Bifurcation%29.ipynb?flush_cache=true). Everything works properly so far. Just a little bit confused about the results stored in adata object.

I'm wondering where I could find the documentation for the new attributes (e.g. **branch_id, branch_lam, S0_pseudotime**) stored in adata object. For instance, I'd like to select cells from one branch (S3 -> S0) and order cell by pseudotime. However, I'm not sure which one should I use?

looks forward to your reply. Thank you.

**Comment by huidongchen** [comment]
Hi, thanks for trying STREAM. Sorry about the lack of documentation for the attributes. 

Re your question, `branch_id_alias` and `S0_pseudotime` should suffice in terms of selecting the cells needed. 

`branch_lam` and `branch_id` are both the 'raw' attributes during the structure learning, which are the `lamda`, i.e. the arc-length from the beginning of the curve, and the `id` internally used to label branches. They are preserved just for the purpose of debugging. You most likely won't need them.

Anyhow, thanks for the feedback. We will keep improving it. Hope the above is helpful to you.

**Comment by MingBit** [comment]
Yeah! it's really helpful. Thanks a lot!
Does it mean that the pseudotime at terminal point is sufficient for ordering?
For instance, **S2_pseudotime** can be used for ordering cells from pathway (S3->S1->S2)?

**Comment by huidongchen** [comment]
`S2_pseudotime` means the ordering of all cells when choosing 'S2' as the **starting node**. 

That being said, to order cells along the trajectory (S3->S1->S2), you should consider `S3_pseudotime`. Also you might want to only keep the cells assigned to that path by choosing the cells from branch ('S3','S1') and ('S1','S2')

**Comment by MingBit** [comment]
Score! Thank you so much! :+1:
