### ISSUE TITLE
Is there a way to label UMAPs produced by STREAM?

### ISSUE THREAD

**Issue by smk5g5** [pinellolab/STREAM#85]
I want to label the UMAPs produced by STREAM same way I can label UMAPs in Seurat with Clustering info/Cell type/batches etc. I was wondering if it is possible to do the same in STREAM and how?

![image](https://user-images.githubusercontent.com/6811915/89091504-e54bc480-d36f-11ea-9228-e4c99f7754ce.png)

Thanks!

**Comment by huidongchen** [comment]
It should be trivial to do that. You can simply specify the parameter `color` in any plotting related function. 

E.g.  `st.plot_dimension_reduction(adata,color=['label','n_genes','your_seruat_clusters'],show_graph=False,show_text=False)`

More examples can be found in our latest [tutorials](https://github.com/pinellolab/STREAM#tutorial)

**Comment by smk5g5** [comment]
I don't think you got my question. I was trying to ask how to put cluster numbers on the UMAP like in the above figure.
