### ISSUE TITLE
Open a precomputed dataset on webapp for visualisation only

### ISSUE THREAD

**Issue by LouisFaure** [pinellolab/STREAM#9]
Hi, 

First of all thank you for this great tool! I managed to apply the analysis process on my dataset from your website and I downloaded the results zip file, including DE and transitionnal gene analysis. I now have a folder having my data files, all result figures and data, and the precomputed folder. 

My problem is that I can't find the way to visualise my results again on a new web server on my side using docker command. My guess was to run the command STREAM_webapp in the same folder as the results, but data does not show up on the precomputed dataset list. Am I doing something wrong? Or does this require another type of command ?

Best Wishes,

Louis Faure

**Comment by huidongchen** [comment]
Hi Louis,

Sorry about the figure issues. You did nothing wrong! The website is currently hosted in a small machine so to accelerate the computation and save space, we only stored the coordinates of cells and curves instead of printing out them in pdf files. Unfortunately right now it doesn't support visualization directly based on the folder you got. (But we will update our website in the very near future. I think it's a good point. We will definitely consider it)

In order to get the visualization results, you can: 

1) run docker commands STREAM directly (not STREAM_webapp). This would by default save all the figures in pdf files
2) download the figures from interactive websites (You can either try our website or run the website locally)
3) Use stream package. We have a bioconda package available https://bioconda.github.io/recipes/stream/README.html. You can find a straightforward tutorial here  https://www.dropbox.com/sh/bx6mnndxgy9tus0/AABs5zWjSBKZa635hSwysKrSa?dl=0

Hope the above is useful to you.

Best,
Huidong

**Comment by LouisFaure** [comment]
Thanks for your fast answer! Maybe I was not clear in my first message, but I did obtain figures from your website, I have all the pdf/png files. My concern was that I can't manage to read the results using a locally made webserver,since you said that that your website does not support visualisation of local folders, I assume this is the same for a locally made webserver (and it will indeed be nice to add this new visualisation feature).

Thank you very much for the conda package, this will be helpfull!

BW,

Louis

**Comment by lucapinello** [comment]
Hi Louis,

I think it is possible. Jon in CC  can provide you with more details but
essentially you need to do the following:

Assuming you have your results in the folder /Users/louis/stream/results

You need to mount that folder inside the docker image under
/STREAM/precomputed i.e.

docker run -p 10001:10001 \

-v /Users/louis/stream/results:/STREAM/precomputed \

-it pinellolab/stream STREAM_webapp


Then open localhost:10001 with your web browser.

This should work.

Please let me know how it goes.

Thanks,

Luca

**Comment by LouisFaure** [comment]
Hi Luca,

Thanks for your answer and your help, I did tried what you proposed, with the following command on Windows:

docker run -p 10001:10001 -v C:\Users\Louis\Downloads\stream-outputs\STREAM_result\Precomputed -it pinellolab/stream STREAM_webapp

Data still does no show up on the pre-computed section (there is nothing on the list)

BW,

Louis

**Comment by lucapinello** [comment]
Hi Louis,

The path is case sensitive (so Precomputed is different than precomputed)
and also not correct.

Each folder with results must be mounted inside the docker image under
/STREAM/precomputed

so in your case, the folder STREAM_result should be in

/STREAM/precomputed/STREAM_result

Now assuming the results are in
C:\Users\Louis\Downloads\stream-outputs\STREAM_result\

The correct option is:

-v C:\Users\Louis\Downloads\stream-outputs\:/STREAM/precomputed

If this doesn't work, Jon can suggest an alternative way to make the folder
appear.

Luca

**Comment by LouisFaure** [comment]
Using correct case and the following command is still unsuccessful:
docker run -p 10001:10001 -v C:\Users\Louis\Downloads\stream-outputs\:/STREAM/precomputed -it pinellolab/stream STREAM_webapp

If this can help, here is the folder stucture of my results:

stream-outputs\
├── STREAM_result\
        ├── Precomputed\

BW,

Louis

**Comment by lucapinello** [comment]
Hey Louis,

Happy it works now and thanks a lot for going through this with us!

We will update the code and the documentation with the proposed changes
(Jon please take a look at the proposed changes, they should be trivial to
implement).

Also happy to host your results in the future if you want to have them also
in the public instance of STREAM.

Best,

Luca

**Comment by LouisFaure** [comment]
Hi Luca,

One correction: I tried to reproduce what I said for cell coloring, the issue is in fact different, reverting the names back to the original naming is not the solution: The only way to get the cell coloring back is by compressing the two files in .gz (no need to go back to the original naming), in fact cell name+extension has to be similar than the ones you showed for the example datasets. This also should be easy to fix on your side.

Thanks for the proposal of hosting the results, I will keep that in mind!

BW,

Louis
