### ISSUE TITLE
Assigning Motifs to Kmers

### ISSUE THREAD

**Issue by sylestiel** [pinellolab/STREAM#90]
Hi,

Can you suggest a way to correlate the kmer sequence to Known Motifs?
I would like for it unsubjective if possible.

Thanks in advance!

**Comment by lucapinello** [comment]
Sure you can consider using TomTom for this task:
http://meme-suite.org/meme_5.1.0/doc/tomtom.html

**Comment by sylestiel** [comment]
Which file should I convert to MEME format for this purpose?

Adata or scaled.tsv.gz

If neither which then.

Thanks!

**Comment by sylestiel** [comment]
Thank you it worked!!
