### ISSUE TITLE
Concatenate several anndata

### ISSUE THREAD

**Issue by terooatt** [pinellolab/STREAM#92]
Hi Thank you very much for this package.

I can't seem able to concatenate two adata loaded by stream cmd, how would you do that? Is it possible?

path = '/Volumes/My Passport for Mac/aging/bone_marrow_010-B-03_Cell_19M_F_SPF/'
adata_018_19M_SPF=st.read(file_name= path +'matrix.mtx',
              file_feature=path + 'features.tsv',
              file_sample=path + 'barcodes.tsv',
              file_format='mtx',workdir='./stream_result')    
adata_018_19M_SPF.var.index = adata_018_19M_SPF.var[1].values
adata_018_19M_SPF.var_names_make_unique()

path = '/Volumes/My Passport for Mac/aging/marrow_010-B-06_Cell_19M_F_SPF/'
adata_019_19M_SPF=st.read(file_name= path +'matrix.mtx',
              file_feature=path + 'features.tsv',
              file_sample=path + 'barcodes.tsv',
              file_format='mtx',workdir='./stream_result')    
adata_019_19M_SPF.var.index = adata_019_19M_SPF.var[1].values
adata_019_19M_SPF.var_names_make_unique()

adata = adata_018_19M_SPF.concatenate([adata_018_19M_SPF])

Saving results in: ./stream_result
Saving results in: ./stream_result
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-4feddf69ed1e> in <module>
     15 adata_019_19M_SPF.var_names_make_unique()
     16 
---> 17 adata = adata_018_19M_SPF.concatenate([adata_018_19M_SPF])

~/miniconda3/envs/stream-env/lib/python3.7/site-packages/anndata/_core/anndata.py in concatenate(self, join, batch_key, batch_categories, uns_merge, index_unique, fill_value, *adatas)
   1732             :,
   1733             (
-> 1734                 out.var.columns.str.extract(pat, expand=False)
   1735                 .fillna("")
   1736                 .argsort(kind="stable")

~/miniconda3/envs/stream-env/lib/python3.7/site-packages/pandas/core/accessor.py in __get__(self, obj, cls)
    185             # we're accessing the attribute of the class, i.e., Dataset.geo
    186             return self._accessor
--> 187         accessor_obj = self._accessor(obj)
    188         # Replace the property with the accessor object. Inspired by:
    189         # https://www.pydanny.com/cached-property.html

~/miniconda3/envs/stream-env/lib/python3.7/site-packages/pandas/core/strings.py in __init__(self, data)
   2098 
   2099     def __init__(self, data):
-> 2100         self._inferred_dtype = self._validate(data)
   2101         self._is_categorical = is_categorical_dtype(data.dtype)
   2102         self._is_string = data.dtype.name == "string"

~/miniconda3/envs/stream-env/lib/python3.7/site-packages/pandas/core/strings.py in _validate(data)
   2155 
   2156         if inferred_dtype not in allowed_types:
-> 2157             raise AttributeError("Can only use .str accessor with string values!")
   2158         return inferred_dtype
   2159 

AttributeError: Can only use .str accessor with string values!

**Comment by lucapinello** [comment]
What was the problem?

**Comment by terooatt** [comment]
Hi, I keep on having the errors when I try to concatenate different anndata. Thanks in advance for your help in this matter!

![Screen Shot 2020-10-13 at 23 23 46](https://user-images.githubusercontent.com/13950799/95874094-7f39df80-0dab-11eb-8fe5-48086422caec.png)

**Comment by terooatt** [comment]
I keep on getting the same error when I concatenate several anndata!

![Screen Shot 2020-10-13 at 23 29 12](https://user-images.githubusercontent.com/13950799/95874917-654ccc80-0dac-11eb-9658-74590b3cd694.png)

![Screen Shot 2020-10-13 at 23 29 35](https://user-images.githubusercontent.com/13950799/95874943-6d0c7100-0dac-11eb-82ee-7c0fee140fc3.png)

**Comment by terooatt** [comment]
Pandas updated version solved the issue!
