### ISSUE TITLE
Heatmap colors for plot_stream

### ISSUE THREAD

**Issue by macros29** [pinellolab/STREAM#97]
Is it possible to customize the heatmap colors for the plot_stream function when plotting pseudotime/variables? Such as the ones below:

![heatmap_colors](https://revolution-computing.typepad.com/.a/6a010534b1db25970b01bb0931cd68970d-pi)

**Comment by huidongchen** [comment]
Yes. The color palette can be specified within the function `st.set_figure_params()`

By default, STREAM is using 

`st.set_figure_params(dpi=80,style='white',figsize=[5.4,4.8],
                     rc={'image.cmap': 'viridis'})`.

It is also illustrated in our [tutorial](https://nbviewer.jupyter.org/github/pinellolab/STREAM/blob/master/tutorial/1.1.STREAM_scRNA-seq%20%28Bifurcation%29.ipynb?flush_cache=true) .

You can simply replace 'viridis' with whatever palette you prefer.

**Comment by macros29** [comment]
Thanks a lot, @huidongchen! Sorry I missed that detail going through the tutorial.
